#!/usr/bin/env bash
set -e

root="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CFLAGS="${CFLAGS:-} -pg -fprofile-arcs"
CXXFLAGS="${CXXFLAGS:-} -pg -fprofile-arcs"
export CFLAGS CXXFLAGS
exec bash "$root/build-debug" "$@"
